
## Last commit: 2023-10-31 12:56:35 UTC by admin
interfaces {
    ge-0/0/0 {
        mtu 9216;
        unit 0 {
            family inet {
                address 10.100.255.129/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/1 {
        mtu 9216;
        unit 0 {
            family inet {
                address 10.100.255.131/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/2 {
        mtu 9216;
        unit 0 {
            family inet {
                address 10.100.255.133/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/3 {
        mtu 9216;
        unit 0 {
            family inet {
                address 10.100.255.135/31;
            }
            family iso;
            family mpls;
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.100.255.5/32;
            }
            family iso {
                address 49.0001.0101.0025.5005.00;
            }
        }
    }
}
routing-options {
    autonomous-system 4200009999;
}
protocols {
    bgp {
        group to_pe {
            local-address 10.100.255.5;
            family inet-vpn {
                any;
            }
            cluster 10.100.255.5;
            peer-as 4200009999;
            neighbor 10.100.255.1;
            neighbor 10.100.255.2;
            neighbor 10.100.255.3;
            neighbor 10.100.255.4;
        }
    }
    isis {
        interface ge-0/0/0.0 {
            point-to-point;
            family inet {
                bfd-liveness-detection {
                    minimum-interval 100;
                }
            }
        }
        interface ge-0/0/1.0 {
            point-to-point;
            family inet {
                bfd-liveness-detection {
                    minimum-interval 100;
                }
            }
        }
        interface ge-0/0/2.0 {
            point-to-point;
            family inet {
                bfd-liveness-detection {
                    minimum-interval 100;
                }
            }
        }
        interface ge-0/0/3.0 {
            point-to-point;
            family inet {
                bfd-liveness-detection {
                    minimum-interval 100;
                }
            }
        }
        interface lo0.0 {
            passive;
        }
    }
    ldp {
        interface ge-0/0/0.0;
        interface ge-0/0/1.0;
        interface ge-0/0/2.0;
        interface ge-0/0/3.0;
    }
    mpls {
        interface ge-0/0/0.0;
        interface ge-0/0/1.0;
        interface ge-0/0/2.0;
        interface ge-0/0/3.0;
    }
    lldp {
        interface ge-0/0/0;
        interface ge-0/0/1;
        interface ge-0/0/2;
        interface ge-0/0/3;
    }
}
