
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 172.16.11.1/24;
            }
        }
    }
    ge-0/0/1 {
        mtu 9216;
        unit 0 {
            family inet {
                address 10.100.255.128/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/2 {
        mtu 9216;
        unit 0 {
            family inet {
                mtu 9000;
                address 10.110.255.0/31;
            }
        }
    }
    ge-0/0/3 {
        mtu 9216;
        unit 0 {
            family inet {
                mtu 9000;
                address 10.110.255.2/31;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.100.255.1/32;
            }
            family iso {
                address 49.0001.0101.0025.5001.00;
            }
        }
    }
}
routing-instances {
    dci {
        instance-type vrf;
        protocols {
            bgp {
                group to_dc1 {
                    neighbor 10.110.255.1 {
                        family inet {
                            any;
                        }
                        peer-as 4200001015;
                    }
                    neighbor 10.110.255.3 {
                        family inet {
                            any;
                        }
                        peer-as 4200001016;
                    }
                }
            }
        }
        interface ge-0/0/2.0;
        interface ge-0/0/3.0;
        vrf-target target:64512:1100;
        vrf-table-label;
    }
    mgmt {
        instance-type vrf;
        forwarding-options {
            dhcp-relay {
                server-group {
                    dhcp-server {
                        172.16.10.3;
                    }
                }
                active-server-group dhcp-server;
                group dhcp {
                    interface ge-0/0/0.0;
                }
            }
        }
        interface ge-0/0/0.0;
        vrf-target target:64512:1000;
        vrf-table-label;
    }
}
routing-options {
    route-distinguisher-id 10.100.255.1;
    autonomous-system 4200009999;
}
protocols {
    bgp {
        group to_rr {
            local-address 10.100.255.1;
            family inet-vpn {
                any;
            }
            peer-as 4200009999;
            neighbor 10.100.255.5;
        }
    }
    isis {
        interface ge-0/0/1.0 {
            point-to-point;
            family inet {
                bfd-liveness-detection {
                    minimum-interval 100;
                }
            }
        }
        interface lo0.0 {
            passive;
        }
    }
    ldp {
        interface ge-0/0/1.0;
    }
    mpls {
        interface ge-0/0/1.0;
    }
    lldp {
        interface ge-0/0/0;
        interface ge-0/0/2;
        interface ge-0/0/3;
        interface ge-0/0/1;
    }
}
