#allow only from webserver10
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy1
  namespace: lab3
spec:
  podSelector:
    matchLabels:
      app: dbserver
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: webserver10
  

