#allow only from dbadmin
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy2
  namespace: lab3
spec:
  podSelector:
    matchLabels:
      app: dbserver
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 172.16.14.11/32 

  

