---
- name: Upload config into router
  hosts: 
  - all
  roles:
    - juniper.junos
  vars:
    username: admin
    password: admin
    config_filename: "conf/{{ inventory_hostname }}.conf"
  connection: local
  gather_facts: no
  tasks:
    - name: create configuration from template
      template: src="underlay_bgp.j2" dest={{config_filename}}
    - name: upload config into router
      juniper_junos_config:
        host: "{{ ansible_host }}"
        user: "{{ username }}"
        password: "{{ password}}"
        file: "{{ config_filename}}"
        config_mode: "exclusive"
        load: "merge"
        format: "text"
    # - name: upload config into router
    #   juniper.device.config:
    #     user: "{{ username }}"
    #     passwd: "{{ password }}"
    #     src: "conf/{{inventory_hostname}}.conf"
    #     config_mode: "exclusive"
    #     load: "merge"
    #     format: "text"