- name: configure vjunosRouter
  hosts:
  - all
  vars:
    username: admin
    conf_dir: "./config"
    conf_file: "{{ conf_dir }}/{{ inventory_hostname }}.set"
  connection: local
  gather_facts: no
  tasks:
  - name: upload config into router
    juniper.device.config:
        host: "{{ ansible_host }}"
        user: "{{ username }}"
        file: "ocssh.set"
        config_mode: "exclusive"
        load: "set"