---
- name: hosts
  hosts:
  - node0
  - node1
  - node2
  - node3
  - client
  - juju
  become: yes
  become_method: sudo
  tasks:
  - name: add hosts
    copy:
      dest: /etc/hosts
      content: |
        127.0.0.1 localhost
        172.16.11.100 client
        172.16.11.101 juju
        172.16.11.110 node0
        172.16.11.111 node1
        172.16.11.112 node2
        172.16.11.113 node3

        # The following lines are desirable for IPv6 capable hosts
        ::1 ip6-localhost ip6-loopback
        fe00::0 ip6-localnet
        ff00::0 ip6-mcastprefix
        ff02::1 ip6-allnodes
        ff02::2 ip6-allrouters
        ff02::3 ip6-allhosts
  - name: change file mode /home/ubuntu/.ssh/id_rsa
    ansible.builtin.file:
      path: /home/ubuntu/.ssh/id_rsa
      owner: ubuntu
      group: ubuntu
      mode: '0600'
  - name: change file mode /root/.ssh/id_rsa
    ansible.builtin.file:
      path: /root/.ssh/id_rsa
      owner: root
      group: root
      mode: '0600'
  - name: Copy file with owner and permissions, ubuntu
    ansible.builtin.copy:
      src: /home/ubuntu/.ssh/authorized_keys
      dest: /home/ubuntu/.ssh/id_rsa.pub
      remote_src: yes
      owner: ubuntu
      group: ubuntu
      mode: '0600'
  - name: Copy file with owner and permissions, root
    ansible.builtin.copy:
      src: /root/.ssh/authorized_keys
      dest: /root/.ssh/id_rsa.pub
      remote_src: yes
      owner: root
      group: root
      mode: '0600'