---
- name: Updating system
  hosts:
    - all
  become: yes
  become_method: sudo
  tasks:
  - name: apt -y update
    apt:
      update_cache: true
      cache_valid_time: 3600
      force_apt_get: true
  - name: apt -y upgrade
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: true
  - name: installing openvswitch
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - openvswitch-switch
      - openvswitch-common
  - name: reboot node
    ansible.builtin.reboot:
      msg: "Rebooting machine in 5 seconds"
  
  
