---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csrx-no-nat
  namespace: lab4
data:
  csrx_config: |
    security {
        policies {
            from-zone right to-zone left {
                policy allow_ping {
                    match {
                        source-address any;
                        destination-address any;
                        application junos-ping;
                    }
                    then {
                        permit;
                    }
                }
            }
            from-zone left to-zone right {
                policy allow_any {
                    match {
                        source-address any;
                        destination-address any;
                        application any;
                    }
                    then {
                        permit;
                    }
                }
            }
        }
        zones {
            security-zone left {
                interfaces {
                    ge-0/0/0.0 {
                        host-inbound-traffic {
                            system-services {
                                ping;
                            }
                        }
                    }
                }
            }
            security-zone right {
                interfaces {
                    ge-0/0/1.0;
                }
            }
        }
    }
  csrx_license: |
    DemoLabJUNOS328441235 aeaqic bfajc4 utglxi behssm zo5aeg 6kjtf3
                      uattzj gmxoqc qd7mut glxibb 3ssmzo 5awerr
                      gaytam rqge4t ambqgi wu66tf mr4aye ckovxg
                      s4dfoi qes3tu mvzg4y lma4uc xosoej uual53
                      mbutwi aty4do e3yttu dccuj5 4ujrrs 5yiec5
                      5esdzp 32mo6w ui7fwo y