---
apiVersion: v1
kind: Pod
metadata:
  name: crpd
  namespace: lab4
  labels:
    app: service-instances
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "vn-left" },
      {"name": "vn-right" }
    ]'
spec:
  containers: 
    - name: crpd
      image: 172.16.14.10:5000/crpd:21.4R1.12
      imagePullPolicy: Always
      ports:
        - containerPort: 179
      securityContext:
        privileged: true
  nodeName: node3

