# vn-ns-default.yaml
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  name: public5
  annotations:
    juniper.net/networks: '{
        "ipamV4Subnet": "172.16.1.48/28",
        "fabricSNAT": false,
        "importRouteTargetList" : ["target:64512:10000"], 
        "exportRouteTargetList" : ["target:64512:10005"]
    }'
  labels: 
    service.contrail.juniper.net/externalNetworkSelector: default-external
  namespace: contrail
spec:
  config: '{
    "cniVersion": "0.3.1", 
    "type": "contrail-k8s-cni"
  }'

