# vn-ns-default.yaml
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  name: public1
  annotations:
    juniper.net/networks: '{
        "ipamV4Subnet": "172.16.1.0/28",
        "fabricSNAT": false,
        "importRouteTargetList" : ["target:64512:10000"], 
        "exportRouteTargetList" : ["target:64512:10001"]
    }'
  namespace: contrail-k8s-kubemanager-k8s-contrail
  labels: 
    service.contrail.juniper.net/externalNetwork: default-external
    # service.contrail.juniper.net/externalNetworkSelector: public1
spec:
  config: '{
    "cniVersion": "0.3.1", 
    "type": "contrail-k8s-cni"
  }'

