---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  name: blue
  namespace: lab4
  annotations:
    juniper.net/networks: '{
        "ipamV4Subnet": "192.168.101.0/24",
        "fabricSNAT": false, 
        "importRouteTargetList" : ["target:64512:20001"], 
        "exportRouteTargetList" : ["target:64512:20001"]
    }'
spec:
  config: '{
    "cniVersion": "0.3.1", 
    "type": "contrail-k8s-cni"
  }'
---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  name: red
  namespace: lab4
  annotations:
    juniper.net/networks: '{
        "ipamV4Subnet": "192.168.102.0/24",
        "fabricSNAT": false,
        "importRouteTargetList" : ["target:64512:10000"], 
        "exportRouteTargetList" : ["target:64512:10003"]
    }'
spec:
  config: '{
    "cniVersion": "0.3.1", 
    "type": "contrail-k8s-cni"
  }'

