---
apiVersion: v1
kind: Namespace
metadata:
  name: lab4
  labels:
    core.juniper.net/isolated-namespace: "true"
  #annotations:
  #  core.juniper.net/forwarding-mode: "fabric-snat"
---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  name: blue
  namespace: lab4
  annotations:
    juniper.net/networks: '{
        "ipamV4Subnet": "192.168.101.0/24",
        "fabricSNAT": false,
        "importRouteTargetList" : ["target:64512:10001"], 
        "exportRouteTargetList" : ["target:64512:10003"],
        "disableBGPaaSIPAutoAllocation" : true,
        "bgpaasPrimaryIP" : "192.168.101.2"
    }'
spec:
  config: '{
    "cniVersion": "0.3.1", 
    "type": "contrail-k8s-cni"
  }'
