#service-web-lb.yaml 
apiVersion: v1
kind: Service
metadata:
  name: ns1-service3
  namespace: ns1
spec:
  selector:
    app: webserver1
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80

