# old one
---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  name: public2
  namespace: ns2
  annotations:
    juniper.net/networks: '{
        "ipamV4Subnet": "172.16.1.16/28",
        "fabricSNAT": false,
        "importRouteTargetList" : ["target:64512:10000"], 
        "exportRouteTargetList" : ["target:64512:10002"]
    }'
  labels: 
    service.contrail.juniper.net/externalNetwork: public2
    # service.contrail.juniper.net/externalNetworkSelector: public2
spec:
  config: '{
    "cniVersion": "0.3.1", 
    "type": "contrail-k8s-cni"
  }'

