cat << EOF | sudo tee /etc/netplan/02_net.yaml
network:
  ethernets:
    eth1:
      dhcp4: no
      mtu: 9000
    eth2:
      dhcp4: no
      mtu: 9000
    eth3:
      dhcp4: no
      mtu: 9000
  bonds:
    bond0:
      macaddress: 56:04:1b:00:33:ef
      mtu: 9000
      interfaces:
        - eth1
        - eth2
      parameters:
         mode: 802.3ad
  bridges:
    ovs1:
      openvswitch: {}
      interfaces:
        - bond0
    ovs2:
      openvswitch: {}
      interfaces:
        - eth3
EOF
