cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
    ethernets:
        enp1s0:
            dhcp4: false
            addresses: [ 192.168.41.10/24]
            routes:
            - to: 0.0.0.0/0
              via: 192.168.41.10
            nameservers:
              addresses:  [10.49.32.95, 10.49.32.97]
    version: 2
EOF

cat << EOF | sudo tee /etc/hostname
dhcp
EOF

