apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard-deployment
  labels:
    app: kuard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard-pod
        image: gcr.io/kuar-demo/kuard-amd64:blue
        ports:
        - containerPort: 8080
        livenessProbe:
            httpGet:
                path: /healthy
                port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: kuard-deploy-service
spec:
  type: LoadBalancer
  ports:
  - name: kuard-web
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: kuard