network:
  ethernets:
    eth0:
      addresses : ['172.16.10.20/24']
      nameservers:
         addresses: ['10.49.32.95', '10.49.32.97']
      routes: 
       - to: 0.0.0.0/0
         via: 172.16.10.254
         metric: 1
       
       
    eth1:
      dhcp4: false
      mtu: 9000
       
    eth2:
      dhcp4: false
      mtu: 9000
       
    eth3:
      dhcp4: false
      mtu: 9000
       
    eth4:
      dhcp4: false
      mtu: 9000
       
    eth5:
      dhcp4: false
      mtu: 9000
       
    eth6:
      dhcp4: false
      mtu: 9000
       
    eth7:
      dhcp4: false
      mtu: 9000
       
    eth8:
      dhcp4: false
      mtu: 9000
       
    eth9:
      dhcp4: false
      mtu: 9000
       
    eth10:
      dhcp4: false
  bridges:
    pe11ge0:
      openvswitch: {}
      interfaces: [ eth1 ]
    pe12ge0:
      openvswitch: {}
      interfaces: [ eth2 ]
    pe13ge0:
      openvswitch: {}
      interfaces: [ eth3 ]
    pe14ge0:
      openvswitch: {}
      interfaces: [ eth4 ]
    cust10_pe11: {}
    cust10_pe12: {}
    cust10_pe13: {}
    cust10_pe14: {}
    global_pe11: {}
    global_pe12: {}
    global_pe13: {}
    global_pe14: {}
       
      
