#policy1-do.yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy1
  namespace: ns-user4
spec:
  podSelector:
    matchLabels:
      app: webserver4
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 172.18.0.0/22
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: dbserver4
    ports:
    - protocol: TCP
      port: 80
#policy2-do.yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy2
  namespace: ns-user4
spec:
  podSelector:
    matchLabels:
      app: dbserver4
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: webserver4
    - ipBlock:
        cidr: 172.18.1.10/32
    ports:
    - protocol: TCP
      port: 80
