# vn-ns-default.yaml
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  annotations:
    "opencontrail.org/cidr": "172.16.4.0/24"
  name: vn-external4
  namespace: ns-user4
spec:
  config: '{
    "cniVersion": "0.3.0", 
    "type": "contrail-k8s-cni"
  }'

