---
apiVersion: v1
kind: Namespace
metadata:
  name: lab6
  annotations:
    opencontrail.org/isolation: "true"
    opencontrail.org/fip-pool: "{
      'domain': 'default-domain', 
      'project': 'k8s-lab6', 
      'network': 'k8s-public6-pod-network', 
      'name': 'public6-fip-pool'
    }"
---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  annotations:
    "opencontrail.org/cidr": "172.16.1.48/28"
    "opencontrail.org/ip_fabric_forwarding": "true"
    "opencontrail.org/external": "true"
  name: public6
  namespace: lab6
spec:
  config: '{
    "cniVersion": "0.3.0", 
    "type": "contrail-k8s-cni"
  }'

