apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ubuntu
    matchExpressions:
      - {key: app, operator: In, values: [ubuntu]}
  template:
    metadata:
      name: ubuntu
      labels:
        app: ubuntu
        type: deployment
    spec:
      containers:
        - name: ubuntu
          image: contrailk8sdayone/ubuntu
          env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret1
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret1
                key: password
