#pod-webserver-do-label.yaml
apiVersion: v1 
kind: Pod 
metadata: 
  name: contrail-webserver2
  labels: 
    app: webserver
spec:
  containers:
  - name: contrail-webserver2
    image: contrailk8sdayone/contrail-webserver
  nodeSelector:
    stage: production
