apiVersion: v1
kind: ReplicationController 
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 3
  selector:
    app: webserver
  template:
    metadata:
      name: webserver
      labels:
        app: webserver
        type: rc
    spec:
      containers:
        - name: webserver
          image: contrailk8sdayone/contrail-webserver 
          securityContext:
            privileged: true
          ports:
            - containerPort: 80
