---
cidr_networks:
  container: 172.16.10.0/24
  tunnel: 172.16.12.0/24
  storage: 172.16.13.0/24

used_ips:
  - "172.16.10.1,172.16.10.50"
  - "172.16.12.1,172.16.12.50"
  - "172.16.13.1,172.16.13.50"

global_overrides:
  # The internal and external VIP should be different IPs, however they
  # do not need to be on separate networks.
  external_lb_vip_address: 172.16.10.21
  internal_lb_vip_address: 172.16.10.10
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "geneve"
        range: "1:1000"
        net_name: "geneve"
        group_binds:
          - neutron_ovn_controller
    - network:
        container_bridge: "br-provider"
        container_type: "veth"
        group_binds:
          - neutron_ovn_controller
        net_name: "vlan"
        network_interface: br-vlan
        type: "vlan"
        range: "101:200,301:400"
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute

###
### Infrastructure
###

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  node0:
    ip: 172.16.10.10

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  node0:
    ip: 172.16.10.10

# load balancer
haproxy_hosts:
  node0:
    ip: 172.16.10.10

###
### OpenStack
###

# keystone
identity_hosts:
  node0:
    ip: 172.16.10.10

# cinder api services
storage-infra_hosts:
  node0:
    ip: 172.16.10.10

# glance
image_hosts:
  node0:
    ip: 172.16.10.10

# placement
placement-infra_hosts:
  node0:
    ip: 172.16.10.10

# nova api, conductor, etc services
compute-infra_hosts:
  node0:
    ip: 172.16.10.10

# heat
orchestration_hosts:
  node0:
    ip: 172.16.10.10

# horizon
dashboard_hosts:
  node0:
    ip: 172.16.10.10

# neutron server, agents (L3, etc)
network_hosts:
  node0:
    ip: 172.16.10.10

# nova hypervisors
compute_hosts:
  node1:
    ip: 172.16.10.11
  node2:
    ip: 172.16.10.12
  node3:
    ip: 172.16.10.13

# cinder storage host (LVM-backed)
storage_hosts:
  node4:
    ip: 172.16.10.14
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "172.16.13.14"
