- name: install software on node desktop1
  hosts: 
  - desktop1
  become: yes
  vars:
    user: ubuntu
  tasks:
    - name: install software
      ansible.builtin.apt:
        pkg:
        - ubuntu-desktop-minimal
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
        msg: "Rebooting machine in 5 seconds"