---
apiVersion: v1
kind: Service
metadata:
  name: webserver3a
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webserver3a
---
#rc-webserver-do.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver3a
  labels:
    app: webserver3a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver3a
  template:
    metadata:
      name: webserver3a
      labels:
        app: webserver3a
    spec:
      containers: 
      - name: webserver3
        image: 172.16.14.10:5000/webserver:0.1
        securityContext:
           privileged: true
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver3b
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webserver3b
---
#rc-webserver-do.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver3b
  labels:
    app: webserver3b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver3b
  template:
    metadata:
      name: webserver3b
      labels:
        app: webserver3b
    spec:
      containers: 
      - name: webserver3
        image: 172.16.14.10:5000/webserver:0.1
        securityContext:
           privileged: true
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver3c
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webserver3c
---
#rc-webserver-do.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver3c
  labels:
    app: webserver3c
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver3c
  template:
    metadata:
      name: webserver3c
      labels:
        app: webserver3c
    spec:
      containers: 
      - name: webserver3
        image: 172.16.14.10:5000/webserver:0.1
        securityContext:
           privileged: true
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver3d
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webserver3d
---
#rc-webserver-do.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver3d
  labels:
    app: webserver3d
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver3d
  template:
    metadata:
      name: webserver3d
      labels:
        app: webserver3d
    spec:
      containers: 
      - name: webserver3
        image: 172.16.14.10:5000/webserver:0.1
        securityContext:
           privileged: true
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver3e
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webserver3e
---
#rc-webserver-do.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver3e
  labels:
    app: webserver3e
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver3e
  template:
    metadata:
      name: webserver3e
      labels:
        app: webserver3e
    spec:
      containers: 
      - name: webserver3
        image: 172.16.14.10:5000/webserver:0.1
        securityContext:
           privileged: true
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver3f
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webserver3f
---
#rc-webserver-do.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver3f
  labels:
    app: webserver3f
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver3f
  template:
    metadata:
      name: webserver3f
      labels:
        app: webserver3f
    spec:
      containers: 
      - name: webserver3
        image: 172.16.14.10:5000/webserver:0.1
        securityContext:
           privileged: true
        ports: 
        - containerPort: 80
