- name: configure loadbalancing
  hosts:
    - all
  roles:
    - juniper.junos
  vars:
    username: admin
  #   conf_dir: "./initial_config"
  #   conf_file: "{{ conf_dir }}/{{ inventory_hostname }}.conf"
  connection: local
  gather_facts: no
  tasks:
    - name: upload config into router
      juniper_junos_config:
        host: "{{ ansible_host }}"
        user: "{{ username }}"
        # file: "{{ conf_file}}"
        config_mode: "exclusive"
        load: "set"
        lines:
        - "set routing-options forwarding-table export pplb"
        - "set policy-options policy-statement pplb then load-balance per-packet"
        # format: "text"