---
- name: Upload config into router
  hosts:
    - all
  roles:
    - juniper.junos
  vars:
    username: admin
    conf_dir: "./tmp"
    conf_file: "{{ conf_dir }}/{{ inventory_hostname }}.conf"
  connection: local
  gather_facts: no
  tasks:
    - name: create config based on template
      template:
        src: jinja2/set_srv6_transport.j2
        dest: "{{ conf_file }}"
    - name: upload config into router
      juniper_junos_config:
        host: "{{ ansible_host }}"
        user: "{{ username }}"
        file: "{{ conf_file}}"
        config_mode: "exclusive"
        load: "set"
        # format: "text"
