---
- name: set interface and routing protocol
  hosts: all
  connection: local
  gather_facts: no
  vars:
    user: admin
  tasks:
    - name: load interface and protocol configuration
      juniper.device.config:  
        template: set_intf.j2
        format: text
        load: merge
        vars: "{{ lookup('file', playbook_dir + '/vars_' + inventory_hostname + '.yaml') | from_yaml}}"
