apiVersion: v1
kind: Pod
metadata:
  name: red-net-client
  namespace: multinet
  annotations:
    k8s.v1.cni.cncf.io/networks: red-vn
spec:
  containers:
    - name: red-net-client
      image: us.gcr.io/inet-science/debugger:latest
      command: ["/bin/sh", "-ec", "ip route add 192.168.128.0/24 via 192.168.255.1; while :; do echo '.'; sleep 5 ; done"]
      securityContext:
        privileged: true
