---
#service-web-nodeport
apiVersion: v1
kind: Service
metadata:
  name: webserver1
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32001
  selector:
    app: webserver1
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver1
  labels:
    app: webserver1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver1
    matchExpressions:
      - {key: app, operator: In, values: [webserver1]}
  template:
    metadata:
      name: webserver1
      labels:
        app: webserver1
    spec:
      containers: 
      - name: webserver1
        image: m1r24n/webserver:0.1
        imagePullPolicy: IfNotPresent 
        securityContext:
           privileged: true
        ports: 
        - containerPort: 80

