---
- name: Upload config into router
  hosts:
    - all
  roles:
    - juniper.junos
  vars:
    username: admin
    password: pass01
    conf_dir: "./junos_config"
    conf_file: "{{ conf_dir }}/{{ inventory_hostname }}.conf"
  connection: local
  gather_facts: no
  tasks:
    - name: upload config into router
      juniper_junos_config:
         host: "{{ ansible_host }}"
         user: "{{ username }}"
         password: "{{ password }}"
         file: "{{ conf_file}}"
         config_mode: "exclusive"
         load: "merge"
         format: "text"
