---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: test3
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "blue" }
    ]'
spec:
  containers:
  - name: pod1
    image: 172.16.14.10:5000/webserver:0.1
    imagePullPolicy: Always 
    securityContext:
      privileged: true
    command: [ 'sh']
    args: ['-c','ip route delete default; ip route add default via 192.168.101.1; python3 /workingdir/webserver.py']
  nodeName: node1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: test3
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "red" }
    ]'
spec:
  containers:
  - name: pod2
    image: 172.16.14.10:5000/webserver:0.1
    imagePullPolicy: Always 
    securityContext:
      privileged: true
    command: [ 'sh']
    args: ['-c','ip route delete default; ip route add default via 192.168.102.1; python3 /workingdir/webserver.py']
  nodeName: node3

