---
apiVersion: v1
kind: Namespace
metadata:
  name: test3
  labels:
    core.juniper.net/isolated-namespace: "true"
---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  name: blue
  namespace: test3
  annotations:
    juniper.net/networks: '{
        "ipamV4Subnet": "192.168.101.0/24",
        "fabricSNAT": false, 
    }'
spec:
  config: '{
    "cniVersion": "0.3.1", 
    "type": "contrail-k8s-cni"
  }'
---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  name: red
  namespace: test3
  annotations:
    juniper.net/networks: '{
        "ipamV4Subnet": "192.168.102.0/24",
        "fabricSNAT": false,
    }'
spec:
  config: '{
    "cniVersion": "0.3.1", 
    "type": "contrail-k8s-cni"
  }'
---
apiVersion: v1
kind: Pod
metadata:
  name: client1
  namespace: test3
  annotations:
    k8s.v1.cni.cncf.io/networks: blue
spec:
  containers:
  - name: webserver
    image: 172.16.14.10:5000/webserver:0.1
    imagePullPolicy: Always 
    securityContext:
      privileged: true
  nodeName: node1
---
apiVersion: v1
kind: Pod
metadata:
  name: client2
  namespace: test3
  annotations:
    k8s.v1.cni.cncf.io/networks: red
spec:
  containers:
  - name: webserver
    image: 172.16.14.10:5000/webserver:0.1
    imagePullPolicy: Always 
    securityContext:
      privileged: true
  nodeName: node2




