apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vm1
  name: vm1
  namespace: test2
spec:
  domain:
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
      interfaces:
      - name: default
        bridge: {}
    resources:
      requests:
        memory: 256M
  networks:
  - name: default
    pod: {}
  volumes:
  - name: containerdisk
    containerDisk:
      image: 172.16.14.10:5000/cirros:0.6.1
      path: /cirros.img
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |
        #cloud-config
        
