---
apiVersion: v1
kind: Namespace
metadata:
  name: ns3
  annotations:
    opencontrail.org/isolation: "true"
    opencontrail.org/fip-pool: "{
      'domain': 'default-domain', 
      'project': 'k8s-ns3', 
      'network': 'k8s-public3-pod-network', 
      'name': 'public3-fip-pool'
    }"
---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  namespace: ns3
  annotations:
    "opencontrail.org/cidr": "172.16.1.32/28"
  name: public3
spec:
  config: '{
    "cniVersion": "0.3.0", 
    "type": "contrail-k8s-cni"
  }'


