#service-web-lb.yaml 
apiVersion: v1
kind: Service
metadata:
  name: service-web-5
  namespace: ns2
spec:
  selector:
    app: webserver5
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
---
#rc-webserver-do.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver5
  namespace: ns2
  labels:
    app: webserver5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver5
    matchExpressions:
      - {key: app, operator: In, values: [webserver5]}
  template:
    metadata:
      name: webserver5
      labels:
        app: webserver5
    spec:
      containers: 
      - name: webserver5
        image: 172.16.14.10:5000/webserver:0.1
        imagePullPolicy: IfNotPresent 
        securityContext:
           privileged: true
        ports: 
        - containerPort: 80

