# vn-ns-default.yaml
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  annotations:
    "opencontrail.org/cidr": "172.16.1.16/28"
  name: public2
spec:
  config: '{
    "cniVersion": "0.3.0", 
    "type": "contrail-k8s-cni"
  }'

