---
- name: set bgp on PE
  hosts: pe
  connection: local
  gather_facts: no
  vars:
    user: admin
  tasks:
    - name: load bgp configuration
      juniper.device.config:  
        template: set_bgp.j2
        format: text
        load: merge
        vars: "{{ lookup('file', playbook_dir + '/vars_' + inventory_hostname + '.yaml') | from_yaml}}"
- name: add configuration on p5
  hosts: 
  - p5
  connection: local
  gather_facts: no
  vars:
    user: admin
  tasks:
    - name: load configuration into p5
      juniper.device.config:  
        load: set
        lines:
        - "set routing-options static route 172.16.11.0/24 next-hop 172.16.13.254"
        - "set routing-options static route 172.16.12.0/24 next-hop 172.16.13.254"
        - "set routing-options static route 192.168.199.0/24 next-hop 172.16.13.254"
        - "set policy-options policy-statement to_isis term 1 from protocol static"
        - "set policy-options policy-statement to_isis term 1 then accept"
        - "set protocols isis export to_isis"
        - "set protocols bgp group to_RD type internal"
        - "set protocols bgp group to_RD local-address 10.100.255.15"
        - "set protocols bgp group to_RD passive"
        - "set protocols bgp group to_RD family traffic-engineering unicast"
        - "set protocols bgp group to_RD export TE"
        - "set protocols bgp group to_RD local-as 65101"
        - "set protocols bgp group to_RD allow 172.16.11.0/24"
        - "set policy-options policy-statement TE term 1 from family traffic-engineering"
        - "set policy-options policy-statement TE term 1 then accept"
        - "set protocols mpls traffic-engineering database import policy TE"

