---
- name: Updating system
  hosts:
    - all
  become: yes
  become_method: sudo
  tasks:
  - name: apt -y update
    apt:
      update_cache: true
      cache_valid_time: 3600
      force_apt_get: true
  - name: apt -y upgrade
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: true
  # - name: add into /etc/hosts
  #   ansible.builtin.blockinfile:
  #     path: /etc/hosts
  #     block: |
  #       172.16.11.111 node1
  #       172.16.11.112 node2
  #       172.16.11.113 node3
  #       172.16.11.114 node4
  #       172.16.11.115 node5
  #       172.16.11.101 lxc
  #       172.16.11.1 gw
- name: install openstack via snap
  hosts:
  - os
  become: yes
  become_method: sudo
  tasks:
  - name: installing openstack using snap
    community.general.snap:
        name: openstack
        state: present
- name: install application on LXC
  hosts:
  - lxc
  become: yes
  become_method: sudo
  tasks:
  - name: installing application using apt
    ansible.builtin.apt:
      pkg:
      - openvswitch-switch
      - openvswitch-common

  
  
