---

- name: updating node with ubuntu OS
  hosts: ubuntu
  become: yes
  vars:
    user: ubuntu
  tasks:
    - name: update and upgrade repository
      ansible.builtin.apt:
        update_cache: true
        upgrade: yes
        state: latest
- name: install software on node gw
  hosts: 
  - gw
  become: yes
  vars:
    user: ubuntu
  tasks:
    - name: install software
      ansible.builtin.apt:
        pkg:
        - novnc
        - websockify
        - wireguard-tools
    - name: Add entries into /etc/coredns/vmmlab.com.db
      ansible.builtin.blockinfile:
        path: /etc/coredns/vmmlab.com.db
        marker: "; {mark} ANSIBLE MANAGED BLOCK"
        block: |
          br1 IN A 172.16.10.21
          br2 IN A 172.16.10.22
          br3 IN A 172.16.10.23
          pe1 IN A 10.100.255.1
          pe2 IN A 10.100.255.2
          pe3 IN A 10.100.255.3
          pe4 IN A 10.100.255.4
          pe5 IN A 10.100.255.5
          p1 IN A 10.100.255.11
          p2 IN A 10.100.255.12
          p3 IN A 10.100.255.13
          p4 IN A 10.100.255.14
          p5 IN A 10.100.255.15
          crpd IN A 10.100.255.10
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
        msg: "Rebooting machine in 5 seconds"
