---
apiVersion: v1
kind: Pod
metadata:
  name: csrx2 
  labels:
    app: service-instances
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "vn-left" },
      {"name": "vn-right" }
    ]'
spec:
  containers: 
    - name: csrx2
      image: 172.16.14.10:5000/csrx:21.3R1.9
      imagePullPolicy: Always
      env: 
      - name: CSRX_ROOT_PASSWORD
        value: "pass01"
      - name: CSRX_SIZE
        value: "medium"
      securityContext:
        privileged: true
