#ns-user.yaml 
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    opencontrail.org/isolation: "true"
    opencontrail.org/fip-pool: "{
      'domain': 'default-domain', 
      'project': 'k8s-ns-user5', 
      'network': 'k8s-vn-external5-pod-network', 
      'name': 'pool-vn-external5'
    }" 
  name: ns-user5
