---
apiVersion: v1
kind: Pod
metadata:
  name: server5
  namespace: ns-user5
  labels:
    app: server5
    do: multinic
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "vn-left" },
      {"name": "vn-right" }
    ]'
spec:
  containers: 
    - name: server5
      image: contrailk8sdayone/contrail-webserver
      securityContext:
        privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: left
  namespace: ns-user5
  labels:
    app: left
    do: multinic
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "vn-left" }
    ]'
spec:
  containers: 
    - name: left
      image: contrailk8sdayone/contrail-webserver
      securityContext:
        privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: right
  namespace: ns-user5
  labels:
    app: right
    do: multinic
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "vn-right" }
    ]'
spec:
  containers: 
    - name: right
      image: contrailk8sdayone/contrail-webserver
      securityContext:
        privileged: true
