# vn-ns-default.yaml
---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  annotations:
    "opencontrail.org/cidr": "172.16.1.0/24"
  name: vn-external5
  namespace: ns-user5
spec:
  config: '{
    "cniVersion": "0.3.0", 
    "type": "contrail-k8s-cni"
  }'
---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  annotations:
    "opencontrail.org/cidr": "172.16.101.0/24"
  name: vn-left
  namespace: ns-user5
spec:
  config: '{
    "cniVersion": "0.3.0", 
    "type": "contrail-k8s-cni"
  }'
---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  annotations:
    "opencontrail.org/cidr": "172.16.102.0/24"
  name: vn-right
  namespace: ns-user5
spec:
  config: '{
    "cniVersion": "0.3.0", 
    "type": "contrail-k8s-cni"
  }'
