network:
  ethernets:
    eth1:
       addresses: [ 172.16.11.1/24 ]
       mtu: 9000
    eth2:
       addresses: [ 172.16.12.1/24 ]
       mtu: 9000
    eth3:
       addresses: [ 172.16.13.130/31 ]
       mtu: 9000
       routes:
         - to: 172.16.255.1/32
           via: 172.16.13.131
           metric: 1
    eth4:
       addresses: [ 172.16.14.1/24 ]
    eth5:
       dhcp4: false
  vlans:
    vlan1:
       id: 1
       addresses: [ 172.16.13.128/31 ]
       link: eth5
    vlan2:
       id: 2
       addresses: [ 172.16.13.132/31 ]
       link: eth5