LINENUM=`grep -n "#container_images_file" undercloud.conf | cut -f 1 -d ":"`
sed -i -e "${LINENUM}a container_images_file = /home/stack/containers-prepare-parameter.yaml" undercloud.conf
LINENUM=`grep -n "#generate_service_certificate" undercloud.conf | cut -f 1 -d ":"`
sed -i -e "${LINENUM}a generate_service_certificate = false" undercloud.conf
LINENUM=`grep -n "#local_interface" undercloud.conf | cut -f 1 -d ":"`
sed -i -e "${LINENUM}a local_interface=eth1" undercloud.conf
LINENUM=`grep -n "#overcloud_domain_name" undercloud.conf | cut -f 1 -d ":"`
sed -i -e "${LINENUM}a overcloud_domain_name = irzan.com" undercloud.conf
# LINENUM=`grep -n "#undercloud_ntp_servers" undercloud.conf| cut -f 1 -d ":"`
# sed -i -e "${LINENUM}a undercloud_ntp_servers = ntp.juniper.net" undercloud.conf
LINENUM=`grep -n "#local_ip" undercloud.conf | cut -f 1 -d ":"`
sed -i -e "${LINENUM}a local_ip=10.1.101.201/24" undercloud.conf
LINENUM=`grep -n "#cidr" undercloud.conf | cut -f 1 -d ":"`
sed -i -e "${LINENUM}a cidr=10.1.101.0/24" undercloud.conf
LINENUM=`grep -n "#dhcp_end" undercloud.conf| cut -f 1 -d ":"`
sed -i -e "${LINENUM}a dhcp_end = 10.1.101.150" undercloud.conf
LINENUM=`grep -n "#dhcp_start" undercloud.conf| cut -f 1 -d ":"`
sed -i -e "${LINENUM}a dhcp_start = 10.1.101.50" undercloud.conf
LINENUM=`grep -n "#gateway" undercloud.conf| cut -f 1 -d ":"`
sed -i -e "${LINENUM}a gateway = 10.1.101.1" undercloud.conf
LINENUM=`grep -n "#inspection_iprange" undercloud.conf| cut -f 1 -d ":"`
sed -i -e "${LINENUM}a inspection_iprange = 10.1.101.160,10.1.101.200" undercloud.conf
