network:
  ethernets:
    eth0:
      addresses : ['172.16.10.4/24']
      nameservers:
         addresses: ['10.49.32.95', '10.49.32.97']
       
    eth1:
      dhcp4: false
      mtu: 9000
      addresses:
        - 10.100.1.3/31
        - fc00:dead:beef:ffff::3/127
       
    eth2:
      dhcp4: false
      mtu: 9000
      addresses:
        - 10.100.1.7/31
        - fc00:dead:beef:ffff::7/127
       
      
