network:
  ethernets:
    eth0:
      addresses : ['172.16.10.2/24']
      nameservers:
         addresses: ['10.49.32.95', '10.49.32.97']
       
    eth3:
      dhcp4: false
      mtu: 9000
       
    eth1:
      dhcp4: false
      mtu: 9000
      addresses:
        - 10.100.1.4/31
        - fc00:dead:beef:ffff::4/127
       
    eth2:
      dhcp4: false
      mtu: 9000
      addresses:
        - 10.100.1.6/31
        - fc00:dead:beef:ffff::6/127
  vlans:
    eth3.101:
      dhcp4: false
      id: 101
      link: eth3
      addresses:
        - 192.168.12.1/24
        - fc00:dead:beef:a012::1/64
       
      
