apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-vm2
  name: vmi-vm2
  namespace: kubevirt-demo
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      - disk:
          bus: virtio
        name: disk2
      interfaces:
      - name: default
        bridge: {}
    resources:
      requests:
        memory: 1024M
  networks:
  - name: default
    pod: {}
  volumes:
  - containerDisk:
      image: 172.16.14.10:5000/debian:11
      path: /debian-11-generic-amd64.qcow2
    name: containerdisk
  - emptyDisk:
      capacity: 8Gi
    name: disk2
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: pass01
        ssh_pwauth: True
        chpasswd: { expire: False }
    name: cloudinitdisk
