apiVersion: v1
kind: Service
metadata:
  name: vmi-vm1-ssh-svc
  namespace: kubevirt-demo
spec:
  ports:
  - port: 22
    targetPort: 22
#    nodePort: 32022
  selector:
    special: vmi-vm1
  type: LoadBalancer
