LINENUM=`grep -n "#container_images_file" undercloud.conf | cut -f 1 -d ":"`
sed -i -e "${LINENUM}a container_images_file = /home/stack/containers-prepare-parameter.yaml" undercloud.conf
LINENUM=`grep -n "#generate_service_certificate" undercloud.conf | cut -f 1 -d ":"`
sed -i -e "${LINENUM}a generate_service_certificate = false" undercloud.conf
LINENUM=`grep -n "#local_interface" undercloud.conf | cut -f 1 -d ":"`
sed -i -e "${LINENUM}a local_interface=eth1" undercloud.conf
LINENUM=`grep -n "#overcloud_domain_name" undercloud.conf | cut -f 1 -d ":"`
sed -i -e "${LINENUM}a overcloud_domain_name = vmmlab.com" undercloud.conf
LINENUM=`grep -n "#undercloud_ntp_servers" undercloud.conf| cut -f 1 -d ":"`
sed -i -e "${LINENUM}a undercloud_ntp_servers = ntp.juniper.net" undercloud.conf
LINENUM=`grep -n "#local_ip" undercloud.conf | cut -f 1 -d ":"`
sed -i -e "${LINENUM}a local_ip=172.16.12.9/24" undercloud.conf
LINENUM=`grep -n "#cidr" undercloud.conf | cut -f 1 -d ":"`
sed -i -e "${LINENUM}a cidr=172.16.12.0/24" undercloud.conf
LINENUM=`grep -n "#dhcp_end" undercloud.conf| cut -f 1 -d ":"`
sed -i -e "${LINENUM}a dhcp_end = 172.16.12.200" undercloud.conf
LINENUM=`grep -n "#dhcp_start" undercloud.conf| cut -f 1 -d ":"`
sed -i -e "${LINENUM}a dhcp_start = 172.16.12.101" undercloud.conf
LINENUM=`grep -n "#gateway" undercloud.conf| cut -f 1 -d ":"`
sed -i -e "${LINENUM}a gateway =172.16.12.1" undercloud.conf
LINENUM=`grep -n "#inspection_iprange" undercloud.conf| cut -f 1 -d ":"`
sed -i -e "${LINENUM}a inspection_iprange = 172.16.12.201,172.16.12.250" undercloud.conf 
