---
apiVersion: v1
kind: Pod
metadata:
  name: client1
  namespace: lab5
spec:
  containers:
  - name: webserver
    image: 172.16.14.10:5000/webserver:0.1
    imagePullPolicy: Always 
    securityContext:
      privileged: true
