---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  name: left
  namespace: lab5
  annotations:
    juniper.net/networks: '{
        "ipamV4Subnet": "192.168.201.0/24",
        "fabricSNAT": false
    }'
spec:
  config: '{
    "cniVersion": "0.3.1", 
    "type": "contrail-k8s-cni"
  }'
---
apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata:
  name: right
  namespace: lab5
  annotations:
    juniper.net/networks: '{
        "ipamV4Subnet": "192.168.202.0/24",
        "fabricSNAT": false
    }'
spec:
  config: '{
    "cniVersion": "0.3.1", 
    "type": "contrail-k8s-cni"
  }'

