---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: lab5
spec:
  containers:
  - name: webserver
    image: 172.16.14.10:5000/webserver:0.1
    imagePullPolicy: Always 
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-left
  namespace: lab5
  annotations:
    k8s.v1.cni.cncf.io/networks: left
spec:
  containers:
  - name: c1
    image: 172.16.14.10:5000/webserver:0.1
    imagePullPolicy: Always 
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-right
  namespace: lab5
  annotations:
    k8s.v1.cni.cncf.io/networks: right
spec:
  containers:
  - name: c1
    image: 172.16.14.10:5000/webserver:0.1
    imagePullPolicy: Always 
    securityContext:
      privileged: true
