apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vm6
  name: vm6
  namespace: lab5
spec:
  domain:
    ioThreadsPolicy: auto
    devices:
      useVirtioTransitional: true
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
      interfaces:
      - name: default
        bridge: {}
      - name: left
        bridge: {}
      - name: right
        bridge: {}
    cpu:
      cores: 1
    resources:
      requests:
        memory: 2048M
        cpu: "1"
      limits:
        memory: 2048M
        cpu: "1"
  networks:
  - name: default
    pod: {}
  - name: left
    multus:
       networkName: left
  - name: right
    multus:
       networkName: right
  volumes:
  - name: containerdisk
    containerDisk:
      image: 172.16.14.10:5000/ubuntu:22.04
      path: /jammy-server-cloudimg-amd64.img
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |
        #cloud-config
        password: pass01
        ssh_pwauth: True
        chpasswd: { expire: False }
        #ssh_authorized_keys:
        #- "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/+8rkgOc76z0m7Cierw4qUs6bahYgQP4/hyPZGmb/mukCSn7ZvbUM27fX1nRbbP8Z0t+ruF8A5kP5jHOXILCTe2K5+JE9aHbkae5ztSwhxZSYxcSPtN0r8G/B57/4cw5QV7yKjSlQiLXf2EMfIt27/ZGeE402Tntz5v41wsj8C9PtBZvSMcgBWYu/HfE94ShSqsUNvg+FzKaVGhPB4mOzsApPF7Y/zopk7ADB6VkBdqUSblauU0a4aDy/3cwGR2NwOGXcszGzNYU4H6AlIsribpQPXkVs/v6b4NRHzAuKVk2FLLneeWsEKIqCZIWjzJj2ck4aWCM3NkoE86ndbRNyFaaxs67KpzPvPlAOwHU8gINyhzDfVi68xeiN9p8ybj3fI/Vw1W70i4wN2rL1PSupnnPNAX0Ijd9ulmhbAJyO+cjuoURLUR56EjJUYfddzRRRjQO0IMKNPDw0BFFxbt4gc1OnC6bJh2odHb/xbXaVCo361kz2IBoeZ3yFVpTcJH8= irzan@irzan-mbp"
    

   
