apiVersion: v1
kind: Service
metadata:
  name: ssh-into-vm1
  namespace: lab5
spec:
  ports:
  - name: ssh-into-vm
    port: 27017
    nodePort: 30000
    protocol: TCP
    targetPort: 22
  selector:
    special: vm1
  # type: LoadBalancer
  type: NodePort
