---
- name: Upload config into router
  hosts:
    - p5
    - pe1
    - pe2
    - pe3
    - pe4
  roles:
    - juniper.junos
  vars:
    username: admin
    conf_dir: "./bgp"
    conf_file: "{{ conf_dir }}/{{ inventory_hostname }}.conf"
  connection: local
  gather_facts: no
  tasks:
    - name: upload config into router
      juniper_junos_config:
        host: "{{ ansible_host }}"
        user: "{{ username }}"
        file: "{{ conf_file}}"
        config_mode: "exclusive"
        load: "set"
        # format: "text"