set policy-options policy-statement from_static term 1 from protocol static
set policy-options policy-statement from_static term 1 then accept
set policy-options policy-statement from_static term default then accept
set protocols isis export from_static
set routing-options static route 172.16.20.0/28 next-hop 10.100.0.5