policy-options {    
    policy-statement from_static {
        term 1 {
            from protocol static;
            then accept;
        }
        term default {
            then accept;
        }
    }
}
protocols {
    isis {
        export from_static;
    }
}

routing-options {
    static {
        route 172.16.20.0/28 next-hop 172.16.14.0;
    }
    autonomous-system 64500;
}


