apiVersion: v1
kind: Service
metadata:
  name: ssh-into-vm2
  namespace: lab5
spec:
  ports:
  - name: ssh-into-vm
    port: 27017
    nodePort: 30001
    protocol: TCP
    targetPort: 22
  selector:
    special: vm2
  # type: LoadBalancer
  type: NodePort
